package talium.system.twitchCommands.persistence;

import org.jetbrains.annotations.Nullable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.ListCrudRepository;
import talium.system.stringTemplates.Template;

import java.util.List;

public interface TriggerRepo extends ListCrudRepository<TriggerEntity, String> {

    List<TriggerEntity> getAllByisAutoGenerated(boolean isUserTrigger);

    List<TriggerEntity> getAllById(String triggerId);

    @Query(value = "SELECT t.id from TriggerEntity t " +
            "LEFT JOIN Template e ON t.id = e.id " +
            "LEFT JOIN MessagePattern p ON t.id = p.parentTrigger.id " +
            "WHERE t.id ilike %?1% " +
            "OR t.description ilike %?1% " +
            "OR p.pattern ilike %?1% " +
            "OR e.template ilike %?1% " +
            "GROUP BY t.id"
    )
    List<String> searchAllBy(String search);
}
