package talium.system.chatTrigger.controller;

import talium.inputs.Twitch4J.TwitchUserPermission;
import talium.system.chatTrigger.cooldown.ChatCooldown;
import talium.system.chatTrigger.persistence.MessagePattern;
import talium.system.chatTrigger.persistence.TriggerEntity;

import java.util.List;

public record TriggerDTO(
        String id,
        String description,
        List<MessagePatternDTO> patterns,
        TwitchUserPermission permission,
        ChatCooldown userCooldown,
        ChatCooldown globalCooldown,
        boolean isAutoGenerated
) {
    public TriggerDTO(TriggerEntity trigger) {
        this(
                trigger.id,
                trigger.description,
                trigger.patterns.stream().map(MessagePattern::toMessagePatternDTO).toList(),
                trigger.permission,
                trigger.userCooldown,
                trigger.globalCooldown,
                trigger.isAutoGenerated
        );
    }
}

