package talium.system.twitchCommands.persistence;

import org.springframework.data.repository.ListCrudRepository;

import java.util.List;

public interface TriggerRepo extends ListCrudRepository<TriggerEntity, String> {

    List<TriggerEntity> getAllByisAutoGenerated(boolean isUserTrigger);

    List<TriggerEntity> getAllById(String triggerId);
}
