package talium.system.twitchCommands.controller;

import talium.inputs.Twitch4J.TwitchUserPermission;
import talium.system.stringTemplates.TemplateDTO;
import talium.system.twitchCommands.cooldown.ChatCooldown;
import talium.system.twitchCommands.persistence.MessagePattern;
import talium.system.twitchCommands.persistence.TriggerEntity;

import java.util.List;

public record TriggerDTO(
        String id,
        String description,
        MessagePatternDTO[] patterns,
        TwitchUserPermission permission,
        ChatCooldown userCooldown,
        ChatCooldown globalCooldown,
        boolean isAutoGenerated,
        TemplateDTO template
) {
    public TriggerDTO(TriggerEntity trigger) {
        this(
                trigger.id,
                trigger.description,
                trigger.patterns.stream().map(MessagePattern::toMessagePatternDTO).toArray(MessagePatternDTO[]::new),
                trigger.permission,
                trigger.userCooldown,
                trigger.globalCooldown,
                trigger.isAutoGenerated,
                trigger.template.toTemplateDTO()
        );
    }
}

