export interface Trigger {
  pattern: string,
  isRegex: boolean,
  isVisible: boolean,
  isEnabled: boolean,
}

export enum CommandPermission {
  EVERYONE,
  PREDICTIONS_BLUE,
  PREDICTIONS_PINK,
  SUBSCRIBER,
  ARTIST,
  FOUNDER,
  VIP,
  MODERATOR,
  BROADCASTER,
  OWNER,
  SYSTEM
}

export enum CooldownTypes {
  MESSAGES,
  SECONDS
}

export interface CommandCooldown {
  amount: number,
  type: string
}

export interface StringTemplate {
  id: string
  template: string,
}

export interface Command {
  id: string,
  description: string,
  patterns: Trigger[],
  permission: string,
  userCooldown: CommandCooldown,
  globalCooldown: CommandCooldown,
  isAutoGenerated: boolean,
  template: StringTemplate | null,
  varJsonSchema: string
}